# Generated by Django 2.2.7 on 2020-02-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0003_auto_20200220_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentchat',
            name='user',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
