# Generated by Django 2.2.7 on 2020-02-20 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0005_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='reciever',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
