# Generated by Django 2.2.7 on 2020-02-20 17:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0006_auto_20200220_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 17, 14, 32, 589885, tzinfo=utc)),
        ),
    ]
