# Generated by Django 2.2.7 on 2020-02-24 05:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0008_auto_20200223_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 5, 8, 51, 168916, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.CharField(max_length=20),
        ),
    ]
